function myFunction() {
    var links = ["http://irinaspac.com/kea/01-web/responsive%20website/index.html","http://irinaspac.com/kea/01-web/redesigned%20website/index.html","http://irinaspac.com/kea/01-web/redesigned%20website/presentation.pdf","http://irinaspac.com/kea/02-animation/group%20project/personas%20collage%20group%205.pdf","http://irinaspac.com/kea/02-animation/group%20project/Story%20_board_Group_5.pdf","http://irinaspac.com/kea/02-animation/group%20project/Test_report_Group_5.pdf","http://irinaspac.com/kea/02-animation/Interactive%20animation/index.html","http://irinaspac.com/kea/02-animation/Link%20to%20simple%20animation/index.html","http://irinaspac.com/kea/02-animation/projectpool_day1/calculator.html","http://irinaspac.com/kea/02-animation/projectpool_day2/index.html","http://irinaspac.com/kea/02-animation/style%20tile%20and%20story%20idea/style%20tile.jpg","http://irinaspac.com/kea/02-animation/story%20board/story%20board.pdf","http://irinaspac.com/kea/03-UX/business%20model%20canvas.pdf","http://irinaspac.com/kea/03-UX/report.pdf","http://irinaspac.com/kea/03-UX/design%20documenation.pdf","http://irinaspac.com/kea/03-UX/website%20with%20link/intro.html","http://irinaspac.com/kea/03-UX/presentation.pptx","http://irinaspac.com/kea/04-video/A%20story%20told%20with%20moving%20images/Freedom.mp4","http://irinaspac.com/kea/04-video/City%20walk%20and%20meetup/STORYBOARD_Dorm-life.pdf","http://irinaspac.com/kea/04-video/City%20walk%20and%20meetup/Dorm-life.mp4"];
    var names = ["Responsive website","Redesigned website","Presentation of the new website","Personas collage","Story board","Testing report","Interactive animation","Simple animation","My own calculator","Interactive game","Style tile","Story board","Business model canvas","Report","Design documentation","Prototype","Presentation of the app","Video without words","Story board","Dorm life in Copenhagen",];
    for(var i =0; i <links.length; i ++){
        var createA = document.createElement('a');
        var createAText = document.createTextNode((i + 1)+ "- " +names[i]);
        createA.setAttribute('href', links[i]);
        createA.appendChild(createAText);
        document.getElementById("id").appendChild(createA);
}}